# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tbsc's Website
email: No email!
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my website! Here I'll sometimes blog (probably rant) about
  stuff, and show what I'm working on.
  If you want to contact me, please do it through GitHub and not Twitter
  (I just don't really use Twitter)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tbsc.github.io" # the base hostname & protocol for your site
twitter_username: Tbsc__
github_username:  Tbsc

# Build settings
markdown: kramdown
